alone:
  - "\\g{name}\\rs наконец разбавил этот безлюдный мир!"
party:
  - "Ave \\g{name}\\rs!"
  - "Да благославят нас боги... На сервер зашёл \\g{name}\\rs!"
  - "Чёрт бы меня побрал! Это же сам \\g{name}\\rs!"
  - "Рад видеть Его Величество \\g{name}\\rs в добром здравии!"
  - "Привет! Вижу, \\g{name}\\rs ещё не успел познакомиться со смертью?"